services:
  - type: web
    name: fynd-ai-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyA6ZQ-hgxvl0_eQvLQmTa45NUlR6MzUulg
      - key: PYTHON_VERSION
        value: "3.13.0"
